// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CC.Net.Dto.UnitTest;
//
//    var simpleReport = SimpleReport.FromJson(jsonString);

namespace CC.Net.Dto.UnitTest.Simple
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SimpleReport
    {
        [JsonProperty("tests")]
        public List<Test> Tests { get; set; }
    }

    public partial class Test
    {
        [JsonProperty("outcome")]
        public string Outcome { get; set; }

        [JsonProperty("duration")]
        public double Duration { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }
    }

    public partial class SimpleReport
    {
        public static SimpleReport FromJson(string json) => JsonConvert.DeserializeObject<SimpleReport>(json, Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this SimpleReport self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
