#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys

from auth_service.config import Settings
from auth_service.crypto import decrypt_token


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Decrypt a Code Critic auth token using AuthService settings."
    )
    parser.add_argument("token", help="Encrypted token generated by AuthService")
    parser.add_argument(
        "--aes-key",
        dest="aes_key",
        default=None,
        help="Override AUTHSERVICE_AES_KEY instead of reading it from the environment",
    )
    args = parser.parse_args()

    aes_key = args.aes_key or Settings.from_env().aes_key
    if not aes_key:
        print(
            "AUTHSERVICE_AES_KEY is not set and --aes-key was not provided.",
            file=sys.stderr,
        )
        return 1

    payload = decrypt_token(args.token, aes_key)
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
