name: .NET

on:
  push:
    branches: [ master ]
    
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build & Restore
      working-directory: CodeCritic
      run: dotnet build -c Release
      
    - name: CRA
      working-directory: CodeCritic/_client
      run: npm install -g create-react-app node-sass-chokidar

    - name: Publish
      working-directory: CodeCritic
      run: dotnet publish -c Release -o ccnetapp
      
    - name: Tar
      working-directory: CodeCritic
      run: tar -zcvf ccnetapp.tar.gz ccnetapp

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ccnetapp
        path: CodeCritic/ccnetapp.tar.gz
